[mypy]
ignore_missing_imports = True
strict_optional = False
warn_unused_configs = True
allow_redefinition = True
disable_error_code = no-redef

[mypy-pygase.client]
disallow_untyped_defs = True

[mypy-pygase.backend]
disallow_untyped_defs = True

[mypy-pygase.connection]
disallow_untyped_defs = True

[mypy-pygase.event]
disallow_untyped_defs = True

[mypy-pygase.utils]
disallow_untyped_defs = True
